// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrisonApi.Data;

#nullable disable

namespace PrisonApi.Migrations
{
    [DbContext(typeof(PrisonContext))]
    [Migration("20251206193533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrisonApi.Models.CanBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongPhuTrach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CanBos");
                });

            modelBuilder.Entity("PrisonApi.Models.HoSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HoSos");
                });

            modelBuilder.Entity("PrisonApi.Models.KhenThuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhenThuong")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("KhenThuongs");
                });

            modelBuilder.Entity("PrisonApi.Models.KyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKyLuat")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("KyLuats");
                });

            modelBuilder.Entity("PrisonApi.Models.LichSinhHoat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("LichSinhHoats");
                });

            modelBuilder.Entity("PrisonApi.Models.LichSuTruyCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanTen");

                    b.ToTable("LichSuTruyCaps");
                });

            modelBuilder.Entity("PrisonApi.Models.PhamNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucAn")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayVaoTrai")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhongGiamId")
                        .HasColumnType("int");

                    b.Property<string>("TomTatToiPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhongGiamId");

                    b.ToTable("PhamNhans");
                });

            modelBuilder.Entity("PrisonApi.Models.PhongGiam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KhuGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhongGiams");
                });

            modelBuilder.Entity("PrisonApi.Models.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quyens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Quản trị hệ thống",
                            Ten = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Cán bộ quản lý",
                            Ten = "QuanLy"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Nhân viên trại",
                            Ten = "NhanVien"
                        });
                });

            modelBuilder.Entity("PrisonApi.Models.TaiKhoan", b =>
                {
                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HoSoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.HasKey("Ten");

                    b.HasIndex("HoSoId");

                    b.HasIndex("QuyenId");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("PrisonApi.Models.KhenThuong", b =>
                {
                    b.HasOne("PrisonApi.Models.PhamNhan", "PhamNhan")
                        .WithMany("KhenThuongs")
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonApi.Models.KyLuat", b =>
                {
                    b.HasOne("PrisonApi.Models.PhamNhan", "PhamNhan")
                        .WithMany("KyLuats")
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonApi.Models.LichSinhHoat", b =>
                {
                    b.HasOne("PrisonApi.Models.PhamNhan", "PhamNhan")
                        .WithMany()
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonApi.Models.LichSuTruyCap", b =>
                {
                    b.HasOne("PrisonApi.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanTen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("PrisonApi.Models.PhamNhan", b =>
                {
                    b.HasOne("PrisonApi.Models.PhongGiam", "PhongGiam")
                        .WithMany("PhamNhans")
                        .HasForeignKey("PhongGiamId");

                    b.Navigation("PhongGiam");
                });

            modelBuilder.Entity("PrisonApi.Models.TaiKhoan", b =>
                {
                    b.HasOne("PrisonApi.Models.HoSo", "HoSo")
                        .WithMany()
                        .HasForeignKey("HoSoId");

                    b.HasOne("PrisonApi.Models.Quyen", "Quyen")
                        .WithMany()
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSo");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("PrisonApi.Models.PhamNhan", b =>
                {
                    b.Navigation("KhenThuongs");

                    b.Navigation("KyLuats");
                });

            modelBuilder.Entity("PrisonApi.Models.PhongGiam", b =>
                {
                    b.Navigation("PhamNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
